name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 5 * * *' # run at 5 AM UTC, continous integration against master branch

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: master

      - name: Compile and test synchronous
        run: |
          zig build test install sync-examples

      #      - name: Compile and test asynchronous
      #        # if: ${{ matrix.platform != 'windows-latest' }}
      #        run: |
      #          zig build async-examples

      - name: Compile and test udp
        # if: ${{ matrix.platform != 'windows-latest' }}
        run: |
          zig build udp-examples

      - name: Compile and test discovery
        # if: ${{ matrix.platform != 'windows-latest' }}
        run: |
          zig build discovery-examples

      - name: Compile and test udp broadcast
        run: |
          zig build udp-broadcast
